<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-D8Q7906" name="com.RanjanPracticeTest.GeneralStoreTestTwo" tests="4" failures="0" timestamp="20 Sep 2022 18:21:20 GMT" time="20.243" errors="2">
  <testcase name="configureAppium" time="20.218" classname="com.RanjanPracticeTest.GeneralStoreTestTwo">
    <error type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException" message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\supi\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 192.168.102.113] 
Process output: [35m[Appium][39m Welcome to Appium v2.0.0-beta.42
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m&#039;192.168.102.113&#039;[39m }
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at C:\Users\supi\.appium\node_modules\appium-uiautomator2-driver
[35m[HTTP][39m Could not start REST http interface listener. Requested address is not available.
[35m[Appium][[39md Ceobuuldg ]n ot[ 3c5omn[fAipgpuiruem A]pp[i3u9mm  Esrervreorr:.  Ilit&#039;sts enpo EsAsiDDblReNO TthAaVAt IaL :d aridvderer sosr n poltu agvian iltarbielde  1to92 .up16da8.1t0e2 .t1h1e 3s:e4r72v3er
 an[dd efbuagi]le d.[ 3O5rmi[gAinpapli uemr]ro[r3:9 ml i  ste n  aEtA DSeDRNOTAVAIL: address not available 192.168.102.113:4723
rver.setupListenHandle [as _listen2] (node:net:1317:21)
[debug] [35m[Appium][39m     at listenInCluster (node:net:1382:12)
[debug] [35m[Appium][39m     at doListen (node:net:1520:7)
[debug] [35m[Appium][39m     at processTicksAndRejections (node:internal/process/task_queues:84:21)

">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\supi\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 192.168.102.113] 
Process output: [35m[Appium][39m Welcome to Appium v2.0.0-beta.42
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'192.168.102.113'[39m }
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at C:\Users\supi\.appium\node_modules\appium-uiautomator2-driver
[35m[HTTP][39m Could not start REST http interface listener. Requested address is not available.
[35m[Appium][[39md Ceobuuldg ]n ot[ 3c5omn[fAipgpuiruem A]pp[i3u9mm  Esrervreorr:.  Ilit'sts enpo EsAsiDDblReNO TthAaVAt IaL :d aridvderer sosr n poltu agvian iltarbielde  1to92 .up16da8.1t0e2 .t1h1e 3s:e4r72v3er
 an[dd efbuagi]le d.[ 3O5rmi[gAinpapli uemr]ro[r3:9 ml i  ste n  aEtA DSeDRNOTAVAIL: address not available 192.168.102.113:4723
rver.setupListenHandle [as _listen2] (node:net:1317:21)
[debug] [35m[Appium][39m     at listenInCluster (node:net:1382:12)
[debug] [35m[Appium][39m     at doListen (node:net:1520:7)
[debug] [35m[Appium][39m     at processTicksAndRejections (node:internal/process/task_queues:84:21)


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:190)
at Utilities.AppiumUtils.startAppiumServer(AppiumUtils.java:39)
at TestUtils.BaseTest.configureAppium(BaseTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://192.168.102.113:4723/status] to be available after 20013 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:155)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:177)
... 32 more
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)
... 34 more
]]>
    </error>
  </testcase> <!-- configureAppium -->
  <testcase name="validateToastMessage" time="0.000" classname="com.RanjanPracticeTest.GeneralStoreTestTwo">
    <skipped/>
  </testcase> <!-- validateToastMessage -->
  <testcase name="tearDown" time="0.025" classname="com.RanjanPracticeTest.GeneralStoreTestTwo">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at TestUtils.BaseTest.tearDown(BaseTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="noToastMessageShow" time="0.000" classname="com.RanjanPracticeTest.GeneralStoreTestTwo">
    <skipped/>
  </testcase> <!-- noToastMessageShow -->
</testsuite> <!-- com.RanjanPracticeTest.GeneralStoreTestTwo -->
